version: '2'

services:
  gigmapr:
    image: gigmapr
    networks:
      proxy:
        aliases:
          - gigmapr
    environment:
      INDEED_PUB: $INDEED_PUB

  nginx:
    image: nginx:stable
    networks:
      proxy:
        aliases:
         - nginx
    volumes:
      - ~/nginx.conf:/etc/nginx/nginx.conf
      - ~/gigmapr-nginx.conf:/etc/nginx/sites-enabled/gigmapr-nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gigmapr

networks:
  proxy:

