version: '2'

services:
  gigmapr:
    image: gigmapr
    container_name: gigmapr
    restart: always
    networks:
      proxy:
        aliases:
          - gigmapr
    environment:
      INDEED_PUB: $INDEED_PUB

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    networks:
      proxy:
        aliases:
         - nginx
    volumes:
      - ~/docker/nginx.conf:/etc/nginx/nginx.conf
      - ~/docker/gigmapr-nginx.conf:/etc/nginx/sites-enabled/gigmapr-nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gigmapr

  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - ~/docker/registry:/var/lib/registry
    ports:
      - "5000:5000"

networks:
  proxy:
